development:
  adapter: postgresql
  database: jobhopper_development
  host: localhost
  encoding: UTF8
  min_messages: WARNING

test: &test
  adapter: postgresql
  database: jobhopper_test
  host: localhost
  encoding: UTF8
  min_messages: WARNING

production:
  adapter: postgresql
  database: jobhopper_production
  host: localhost
  encoding: UTF8
  min_messages: WARNING